"""
make_catalog.py — Scan data_from_fred/*.zip and write data_from_fred/catalog.yaml.

Reads metadata from inside each zip (ts_shift, frame counts, etc.) without extracting.
Merges with any existing catalog so manual `description` and `drive_file_id` fields
are preserved across runs.

Usage:
    cd c:\\ai_drone

    # Scan local zips → update catalog.yaml:
    python 4channel_project/make_catalog.py

    # Auto-assign splits by percentage (writes splits.yaml):
    python 4channel_project/make_catalog.py --auto-split --train 70 --val 20 --test 10

    # Scan Google Drive folder → add drive_file_id to catalog.yaml:
    python 4channel_project/make_catalog.py --scan-drive
"""

import os
import sys
import fnmatch
import argparse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    import yaml as _yaml
except ImportError:
    print("ERROR: pip install pyyaml"); sys.exit(1)

from zip_utils import ZipSequence

_HERE          = os.path.dirname(os.path.abspath(__file__))
DATA_FROM_FRED = os.path.normpath(os.path.join(_HERE, '..', 'data_from_fred'))
SPLITS_YAML    = os.path.join(DATA_FROM_FRED, 'splits.yaml')
CATALOG_YAML   = os.path.join(DATA_FROM_FRED, 'catalog.yaml')
DRIVE_FOLDER_ID = "1pISIErXOx76xmCqkwhS3-azWOMlTKZMp"


def load_splits():
    if not os.path.isfile(SPLITS_YAML):
        print(f"[warn] splits.yaml not found at {SPLITS_YAML} — all sequences marked 'unassigned'")
        return {}
    with open(SPLITS_YAML) as f:
        data = _yaml.safe_load(f) or {}
    mapping = {}
    for split, seq_list in data.items():
        for s in (seq_list or []):
            mapping[str(s)] = split
    return mapping


def auto_split(train_pct, val_pct, test_pct):
    """
    Automatically assign local zip sequences to train/val/test by percentage.

    Sequences are sorted numerically (reproducible, no randomness).
    Writes data_from_fred/splits.yaml and returns the split dict.
    """
    total = train_pct + val_pct + test_pct
    if total != 100:
        print(f"ERROR: --train + --val + --test must sum to 100 (got {total})")
        sys.exit(1)

    all_seqs = sorted(
        int(f[:-4]) for f in os.listdir(DATA_FROM_FRED)
        if f.endswith('.zip')
    )
    n = len(all_seqs)
    if n == 0:
        print(f"ERROR: No .zip files found in {DATA_FROM_FRED}")
        sys.exit(1)

    n_train = round(n * train_pct / 100)
    n_val   = round(n * val_pct   / 100)

    train_seqs = all_seqs[:n_train]
    val_seqs   = all_seqs[n_train : n_train + n_val]
    test_seqs  = all_seqs[n_train + n_val:]

    splits = {
        'train': train_seqs,
        'val':   val_seqs,
        'test':  test_seqs,
    }

    with open(SPLITS_YAML, 'w') as f:
        f.write(
            f"# FRED sequence splits — auto-generated by make_catalog.py\n"
            f"# --train {train_pct} --val {val_pct} --test {test_pct}\n"
            f"# {n} sequences total, sorted by sequence number.\n"
            f"# Edit manually to reassign sequences between splits.\n\n"
        )
        _yaml.dump(splits, f, default_flow_style=None)

    print(f"Wrote {SPLITS_YAML}  ({n} sequences)")
    print(f"  train : {len(train_seqs):3d} seqs  {train_seqs}")
    print(f"  val   : {len(val_seqs):3d} seqs  {val_seqs}")
    print(f"  test  : {len(test_seqs):3d} seqs  {test_seqs}")
    return splits


def update_drive_ids(folder_id=DRIVE_FOLDER_ID, api_key=None):
    """
    Scan a public Google Drive folder and add drive_file_id to catalog.yaml.

    api_key: free Google API key for reliable listing (recommended).
             Without it, falls back to HTML parsing which often fails.
    Existing catalog entries are updated in-place; other fields are unchanged.
    """
    from gdrive import scan_folder

    print(f"Scanning Drive folder {folder_id} ...")
    id_map = scan_folder(folder_id, api_key=api_key)

    if not id_map:
        print("No Drive file IDs found — catalog.yaml not modified.")
        print("You can add drive_file_id fields manually to catalog.yaml.")
        return

    existing = load_existing_catalog()
    for seq_id, fid in id_map.items():
        if seq_id not in existing:
            existing[seq_id] = {}
        existing[seq_id]['drive_file_id'] = fid
        print(f"  seq {seq_id:>4s} → drive_file_id: {fid}")

    # Re-write catalog preserving all other fields
    split_map = load_splits()
    sequences = {}
    for seq_id, entry in sorted(existing.items(), key=lambda x: int(x[0]) if x[0].isdigit() else 0):
        sequences[seq_id] = {
            'split':          split_map.get(seq_id, entry.get('split', 'unassigned')),
            'zip_size_mb':    entry.get('zip_size_mb', 0),
            'ts_shift_us':    entry.get('ts_shift_us', 0),
            'n_event_frames': entry.get('n_event_frames', 0),
            'n_event_yolo':   entry.get('n_event_yolo', 0),
            'n_rgb_frames':   entry.get('n_rgb_frames', 0),
            'n_rgb_yolo':     entry.get('n_rgb_yolo', 0),
            'drive_file_id':  entry.get('drive_file_id', ''),
            'description':    entry.get('description', ''),
        }

    output = (
        "# FRED Sequence Catalog\n"
        "# Auto-generated by 4channel_project/make_catalog.py\n"
        "# Edit `description` and `drive_file_id` fields manually if needed.\n\n"
        f"{_yaml.dump({'sequences': sequences}, default_flow_style=False, sort_keys=True)}"
    )
    with open(CATALOG_YAML, 'w') as f:
        f.write(output)

    print(f"\nUpdated {CATALOG_YAML}  ({len(id_map)} Drive IDs added/updated)")


def load_existing_catalog():
    if not os.path.isfile(CATALOG_YAML):
        return {}
    with open(CATALOG_YAML) as f:
        data = _yaml.safe_load(f) or {}
    return data.get('sequences', {})


def scan_zip(zip_path, seq_id):
    """Open zip, count members, extract ts_shift_us."""
    zs = ZipSequence(zip_path, os.path.join(DATA_FROM_FRED, seq_id))
    names = zs._names

    n_event_frames = sum(1 for n in names if fnmatch.fnmatch(n, 'Event/Frames/*.png'))
    n_event_yolo   = sum(1 for n in names if fnmatch.fnmatch(n, 'Event_YOLO/*.txt'))
    n_rgb_frames   = sum(1 for n in names if fnmatch.fnmatch(n, 'PADDED_RGB/*.jpg'))
    n_rgb_yolo     = sum(1 for n in names if fnmatch.fnmatch(n, 'RGB_YOLO/*.txt'))
    ts_shift_us    = zs.ts_shift_us
    zs.close()

    zip_size_mb = os.path.getsize(zip_path) // (1024 * 1024)

    return {
        'zip_size_mb':    zip_size_mb,
        'ts_shift_us':    ts_shift_us,
        'n_event_frames': n_event_frames,
        'n_event_yolo':   n_event_yolo,
        'n_rgb_frames':   n_rgb_frames,
        'n_rgb_yolo':     n_rgb_yolo,
    }


def main():
    split_map = load_splits()
    existing  = load_existing_catalog()

    zip_files = sorted(
        f for f in os.listdir(DATA_FROM_FRED)
        if f.endswith('.zip')
    )

    if not zip_files:
        print(f"No .zip files found in {DATA_FROM_FRED}")
        return

    print(f"Found {len(zip_files)} zip(s) in {DATA_FROM_FRED}\n")

    sequences = {}
    for zf in zip_files:
        seq_id   = zf[:-4]   # strip .zip
        zip_path = os.path.join(DATA_FROM_FRED, zf)
        print(f"  Scanning {zf} ...", end=' ', flush=True)

        try:
            info = scan_zip(zip_path, seq_id)
        except Exception as e:
            print(f"ERROR: {e}")
            continue

        split = split_map.get(seq_id, 'unassigned')
        prev  = existing.get(seq_id, {})

        sequences[seq_id] = {
            'split':          split,
            'zip_size_mb':    info['zip_size_mb'],
            'ts_shift_us':    info['ts_shift_us'],
            'n_event_frames': info['n_event_frames'],
            'n_event_yolo':   info['n_event_yolo'],
            'n_rgb_frames':   info['n_rgb_frames'],
            'n_rgb_yolo':     info['n_rgb_yolo'],
            'drive_file_id':  prev.get('drive_file_id', ''),
            'description':    prev.get('description', ''),
        }

        print(f"split={split:10s}  event_frames={info['n_event_frames']:4d}  "
              f"rgb_frames={info['n_rgb_frames']:4d}  "
              f"ts_shift={info['ts_shift_us']:,} µs  "
              f"{info['zip_size_mb']} MB")

    output = (
        "# FRED Sequence Catalog\n"
        "# Auto-generated by 4channel_project/make_catalog.py\n"
        "# Edit `description` and `drive_file_id` fields manually if needed.\n\n"
        f"{_yaml.dump({'sequences': sequences}, default_flow_style=False, sort_keys=True)}"
    )

    with open(CATALOG_YAML, 'w') as f:
        f.write(output)

    print(f"\nWrote {CATALOG_YAML}  ({len(sequences)} sequences)")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="FRED sequence catalog manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python make_catalog.py                            # scan local zips\n"
            "  python make_catalog.py --auto-split               # 70/20/10 split\n"
            "  python make_catalog.py --auto-split --train 60 --val 20 --test 20\n"
            "  python make_catalog.py --scan-drive               # add Drive file IDs\n"
        ),
    )
    parser.add_argument('--auto-split',  action='store_true',
                        help='Auto-assign local zips to train/val/test by percentage, write splits.yaml')
    parser.add_argument('--train',       type=int, default=70,
                        help='Train percentage for --auto-split (default: 70)')
    parser.add_argument('--val',         type=int, default=20,
                        help='Val percentage for --auto-split (default: 20)')
    parser.add_argument('--test',        type=int, default=10,
                        help='Test percentage for --auto-split (default: 10)')
    parser.add_argument('--scan-drive',    action='store_true',
                        help='Scan Google Drive folder and add drive_file_id to catalog.yaml')
    parser.add_argument('--download-all', action='store_true',
                        help='Download ALL zips from Drive folder to data_from_fred/ '
                             '(no API key needed, uses gdown)')
    parser.add_argument('--folder-id',   default=DRIVE_FOLDER_ID,
                        help=f'Google Drive folder ID (default: {DRIVE_FOLDER_ID})')
    parser.add_argument('--api-key',     default=None,
                        help='Google API key for --scan-drive (reliable listing). '
                             'Free at: console.cloud.google.com → Drive API → Credentials')
    args = parser.parse_args()

    if args.auto_split:
        print(f"Auto-split: train={args.train}%  val={args.val}%  test={args.test}%")
        auto_split(args.train, args.val, args.test)
        print()

    if args.download_all:
        from gdrive import download_folder_all
        download_folder_all(args.folder_id, DATA_FROM_FRED)
        print()
        main()   # refresh catalog after download
        sys.exit(0)

    if args.scan_drive:
        update_drive_ids(args.folder_id, api_key=args.api_key)
        sys.exit(0)

    main()
