"""
make_catalog.py — Scan data_from_fred/*.zip and write data_from_fred/catalog.yaml.

Reads metadata from inside each zip (ts_shift, frame counts, etc.) without extracting.
Merges with any existing catalog so manual `description` fields are preserved.

Usage:
    cd c:\\ai_drone
    python 4channel_project/make_catalog.py
"""

import os
import sys
import fnmatch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    import yaml as _yaml
except ImportError:
    print("ERROR: pip install pyyaml"); sys.exit(1)

from zip_utils import ZipSequence

_HERE          = os.path.dirname(os.path.abspath(__file__))
DATA_FROM_FRED = os.path.normpath(os.path.join(_HERE, '..', 'data_from_fred'))
SPLITS_YAML    = os.path.join(DATA_FROM_FRED, 'splits.yaml')
CATALOG_YAML   = os.path.join(DATA_FROM_FRED, 'catalog.yaml')


def load_splits():
    if not os.path.isfile(SPLITS_YAML):
        print(f"[warn] splits.yaml not found at {SPLITS_YAML} — all sequences marked 'unassigned'")
        return {}
    with open(SPLITS_YAML) as f:
        data = _yaml.safe_load(f) or {}
    mapping = {}
    for split, seq_list in data.items():
        for s in (seq_list or []):
            mapping[str(s)] = split
    return mapping


def load_existing_catalog():
    if not os.path.isfile(CATALOG_YAML):
        return {}
    with open(CATALOG_YAML) as f:
        data = _yaml.safe_load(f) or {}
    return data.get('sequences', {})


def scan_zip(zip_path, seq_id):
    """Open zip, count members, extract ts_shift_us."""
    zs = ZipSequence(zip_path, os.path.join(DATA_FROM_FRED, seq_id))
    names = zs._names

    n_event_frames = sum(1 for n in names if fnmatch.fnmatch(n, 'Event/Frames/*.png'))
    n_event_yolo   = sum(1 for n in names if fnmatch.fnmatch(n, 'Event_YOLO/*.txt'))
    n_rgb_frames   = sum(1 for n in names if fnmatch.fnmatch(n, 'PADDED_RGB/*.jpg'))
    n_rgb_yolo     = sum(1 for n in names if fnmatch.fnmatch(n, 'RGB_YOLO/*.txt'))
    ts_shift_us    = zs.ts_shift_us
    zs.close()

    zip_size_mb = os.path.getsize(zip_path) // (1024 * 1024)

    return {
        'zip_size_mb':    zip_size_mb,
        'ts_shift_us':    ts_shift_us,
        'n_event_frames': n_event_frames,
        'n_event_yolo':   n_event_yolo,
        'n_rgb_frames':   n_rgb_frames,
        'n_rgb_yolo':     n_rgb_yolo,
    }


def main():
    split_map = load_splits()
    existing  = load_existing_catalog()

    zip_files = sorted(
        f for f in os.listdir(DATA_FROM_FRED)
        if f.endswith('.zip')
    )

    if not zip_files:
        print(f"No .zip files found in {DATA_FROM_FRED}")
        return

    print(f"Found {len(zip_files)} zip(s) in {DATA_FROM_FRED}\n")

    sequences = {}
    for zf in zip_files:
        seq_id   = zf[:-4]   # strip .zip
        zip_path = os.path.join(DATA_FROM_FRED, zf)
        print(f"  Scanning {zf} ...", end=' ', flush=True)

        try:
            info = scan_zip(zip_path, seq_id)
        except Exception as e:
            print(f"ERROR: {e}")
            continue

        split = split_map.get(seq_id, 'unassigned')
        prev  = existing.get(seq_id, {})

        sequences[seq_id] = {
            'split':          split,
            'zip_size_mb':    info['zip_size_mb'],
            'ts_shift_us':    info['ts_shift_us'],
            'n_event_frames': info['n_event_frames'],
            'n_event_yolo':   info['n_event_yolo'],
            'n_rgb_frames':   info['n_rgb_frames'],
            'n_rgb_yolo':     info['n_rgb_yolo'],
            'description':    prev.get('description', ''),
        }

        print(f"split={split:10s}  event_frames={info['n_event_frames']:4d}  "
              f"rgb_frames={info['n_rgb_frames']:4d}  "
              f"ts_shift={info['ts_shift_us']:,} µs  "
              f"{info['zip_size_mb']} MB")

    catalog = {
        '# FRED Sequence Catalog': None,
        '# Auto-generated by make_catalog.py — edit `description` fields manually': None,
    }

    output = (
        "# FRED Sequence Catalog\n"
        "# Auto-generated by 4channel_project/make_catalog.py\n"
        "# Edit the `description` field for each sequence manually.\n\n"
        f"{_yaml.dump({'sequences': sequences}, default_flow_style=False, sort_keys=True)}"
    )

    with open(CATALOG_YAML, 'w') as f:
        f.write(output)

    print(f"\nWrote {CATALOG_YAML}  ({len(sequences)} sequences)")


if __name__ == '__main__':
    main()
